# spring.application.name=SpringBootCURD

# spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore
# spring.datasource.username=noob_cooder
# spring.datasource.password=SimplePassword123
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.open-in-view=false

# server.port=8080

spring.application.name=SpringBootCURD

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=${PORT:8080}
